### ISSUE TITLE
Ensure that Plugin Preview Page checklist reflects napari community priorities for metadata locations

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#1023]
The plugin preview page still has a checklist item which tells plugin developers to provide a napari-hub-specific description in `napari-hub/DESCRIPTION.md`

This should be modified such that ANY description (whether from PyPI or `napari-hub/DESCRIPTION.md`) satisfies the checkboxes

**Comment by richaagarwal** [comment]
@neuromusic to provide a screenshot.   @manasaV3 @codemonkey800 @klai95 to discuss in next backlog refinement

**Comment by neuromusic** [comment]
screenshot from docs: 
![image](https://user-images.githubusercontent.com/1245615/236052216-61f4c937-1c3f-4fad-8488-c4afafc5ebe1.png)

**Comment by kandarpksk** [comment]
Here's a live example of the plugin Kevin and I made during home week!
https://preview.napari-hub.org/klai95/test-detect-spots/1

**Comment by manasaV3** [comment]
Relevant source code to look into: https://github.com/chanzuckerberg/napari-hub/blob/main/backend/preview/preview.py#L148

**Comment by dgmccart** [comment]
I can update our eng docs [here](https://github.com/chanzuckerberg/napari-hub/wiki/Eng-Tech:-Plugin-Metadata#github-metadata) once these changes have been made.

**Comment by klai95** [comment]
> This might require a spike ticket to figure out the required code changes to use `README.md` cc: @klai95
> 
> #1032

Details of the spike is here: https://github.com/chanzuckerberg/napari-hub/issues/1032#issuecomment-1550487150

**Comment by richaagarwal** [comment]
I've opened a PR here - https://github.com/chanzuckerberg/napari-hub/pull/1082 - but would need someone else to look into testing these changes as these are untested as of now.  A couple notes on this:
- The reason we appear to render the `README.md` as the description on the napari hub site currently is that pypi uses that file to populate its `description` field. However, we don't specifically examine the github `README.md` ourselves (this PR will change that).
- I am assuming the reason for the discrepancy between the napari hub plugin page, and the preview page (in terms of what is available for the `description` field) is due to what is available in the wheel's metadata at the time of the preview page action.  Haven't verified that though. 

I'll leave this in code review for now but if anyone would like to claim testing of these, please do so :)

**Comment by richaagarwal** [comment]
Moving this back into the backlog as we've paused work on this for now

**Comment by richaagarwal** [comment]
Closing this due to a planned upcoming deprecation (see https://github.com/chanzuckerberg/napari-hub/discussions/1216)
