### ISSUE TITLE
Handle updates from dependabot for snowflake-connector-python

### ISSUE THREAD

**Issue by manasaV3** [chanzuckerberg/napari-hub#1069]
Merging changes from https://github.com/chanzuckerberg/napari-hub/pull/1002 cause the causes `AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms' error. `

**Comment by manasaV3** [comment]
The cryptography version updates from the version bump could cause this.  Analyzing the version dependency on the cryptography package would help find a resolution to this.

**Comment by richaagarwal** [comment]
Since the [vulnerability this addresses](https://github.com/chanzuckerberg/napari-hub/security/dependabot/39) requires that an "an attacker is able to supply arbitrary input to the get_file_transfer_type method", and we don't accept user input for our calls to Snowflake, I don't believe this would be a security issue, at the very least. Does that sound right to you, @manasaV3?
