### ISSUE TITLE
General discussion around language used on hub and napari.dev

### ISSUE THREAD

**Issue by tlambert03** [chanzuckerberg/napari-hub#120]
I'm very excited about the upcoming hub release and want to thank you for your efforts!

I'd would, though, like to open a discussion and share some thoughts/concerns on some of the "sales-pitchy/marketing" language that I see used on services like the hub and napari.dev.  First: I think these are both awesome services: I'm super appreciative and I can't wait to see them get off the ground.  I do, however, sometimes find myself feeling uncomfortable as I read them.  Some of the wording comes off sounding like an advertisement, and feels a bit out of place in a scientific environment.  I  _do_ recognize that there is generally language somewhere else on the page that clarifies that "some of this is aspirational", as opposed to "this is already concretely available".  But that approach can feel like a bit of a trick... as though it's left as an exercise to the perceptive reader to realize that you can't _really_ do these things yet.  (I'd kind of prefer that we underpromise/overdeliver... rather than be seen as a community that likes to wrap things in an overly sunny package)

Some examples from the [hub](https://www.napari-hub.org/)

- "plugin users can ... **be confident** they've found the right plugin for their data and **"it just works"**
 
> that feels extremely hard to do ...  and i'm not immediately sure how we can promise that?  if it's anything like most scientific communities, i suspect it will be more like a typical "try some of the more popular plugins until you hit on something that eventually works for you".  no?

- "plugin builders can **capture reliable actionable feedback...**
 
> I mean, I _hope_ that's the case.  but since the feedback is coming from the community, how can we promise that the feedback is either reliable or actionable?

- "Install into napari with confidence"

> feels like marketing talk for "we'll remind you how install plugins" ... but whether they install correctly is out of our hands...

and from [napari.dev](https://www.napari.dev/) ...

- big bold type at the top: "Share your analysis tool with researchers everywhere — No GUI development required."... "napari is designed with researchers’ needs in mind and takes the GUI work off your hands."

> there too, that's an aspiration that we have, but have definitely not achieved... but that's not really clear anywhere on that page at all.  it also makes it sound like napari was designed by some organization that may or may not actually _be_ researchers, but with them as a target market... which is definitely not the case.    This one particularly feels like it needs to be wrapped in a "we hope to someday" sort of preamble

- "Commit your changes. We’ll handle the testing."

> again... that would be amazing... but as we all know... that's proven to be quite challenging, and it reads like we've already achieved it.

Anyway, just want to re-emphasize that I recognize these things are meant to be aspirational, and not necessarily taken literally... but as a core developer on the program being referenced they make me feel a little uncomfortable.  While it probably _does_ work to build excitement, it doesn't quite feel "authentic".  I find myself wondering why it needs to be stated as such.

Hope you don't mind me saying so, and thanks again for the awesome, exciting resource.

**Comment by neuromusic** [comment]
Thanks for reaching out with your concerns, Talley.

The *napari hub* examples you cite from our temporary landing page are explicitly aspirational and we tried to make this clear. This is absolutely what we hope to deliver through our work on the napari hub and through our partnership with napari.

![image (5) (1)](https://user-images.githubusercontent.com/1245615/124039359-a24b0480-d9b7-11eb-9c97-d12e4bb2432b.png)


Now that we’ve launched the full napari hub, we’ll be moving some of this language to a description of our roadmap on Github. Happy to revise some of the language to make it 100% clear that this is our vision and to separate it from the concrete features and value we plan to deliver in the near term.

As for the napari.dev language, you’re right: when we launched napari.dev last year, there were only i/o plugins for napari. We’ve learned a lot since then and decided to prioritize work on the napari hub over developer services and its clear that the language here needs revision to accurately reflect our plans and the state of napari.

![image (6)](https://user-images.githubusercontent.com/1245615/124039438-c4dd1d80-d9b7-11eb-815c-b7b49942bbf4.png)
