### ISSUE TITLE
maintenance metrics don't show on plugin pages

### ISSUE THREAD

**Issue by bnelson-czi** [chanzuckerberg/napari-hub#1265]
#### Description
We checked several plugin pages and maintenance metrics don't seem to show on the Activity tab for any of them. Not sure if this is a problem for all plugin pages or fraction of them.

#### Steps/Code to Reproduce
Go to any plugin page and click the activity tab. PyPI metrics are there, commit activity isn't.

#### Expected Results
I expect to see maintenance metrics.

#### Actual Results
![Screenshot 2023-09-19 at 12 34 16 PM](https://github.com/chanzuckerberg/napari-hub/assets/68256044/3d20c596-1001-4765-aadf-4679dffc1f61)

**Comment by richaagarwal** [comment]
Thanks for reporting, @bnelson-czi!

It looks like the Github API we use to access certain fields on the frontend has been down.  I've been tinkering with some potential workarounds in our dev environment to limit the Github API calls we need to make to load this data, so e.g. in https://dev-shared-frontend.dev.imaging.cziscience.com/plugins/vollseg-napari-trackmate the data mostly loads, but you can still see that it fails to load the created date (see screenshot below). Also, the stars/forks/etc in the sidebar are not loading correctly either. 

I'm going to label this a P1 bug and have @manasaV3 continue to look into what the best workaround would be. 

<img width="874" alt="Screenshot 2023-09-20 at 1 52 56 AM" src="https://github.com/chanzuckerberg/napari-hub/assets/354591/f53fc0f6-46e0-4e5a-aa27-e5e56fe042dc">

**Comment by richaagarwal** [comment]
Update: I've run the octokit js client locally (with the same credentials we use in our dev & production environments) and it works, so I'm not sure why we're failing to fetch the data. Might be worth digging into the frontend logs further.

**Comment by richaagarwal** [comment]
For posterity, the root cause of this issue was not the Github API but this line: https://github.com/chanzuckerberg/napari-hub/pull/1254/files#diff-a8310300fb3525f53f72800da333a35fd2f326430174371d08dce32850e0d59cR62 introduced in a recent release that did not undergo full QA testing. The linked PR addresses this and will be deployed shortly.

**Comment by richaagarwal** [comment]
For posterity, the root cause of this issue was not the Github API, but this line: https://github.com/chanzuckerberg/napari-hub/pull/1254/files#diff-a8310300fb3525f53f72800da333a35fd2f326430174371d08dce32850e0d59cR62 introduced in a recent release. The linked PR addresses this and will be deployed shortly.
