### ISSUE TITLE
Napari hub doesn't seem to support manifest files in subdirectories

### ISSUE THREAD

**Issue by adamltyson** [chanzuckerberg/napari-hub#1300]
#### Description
Napari plugins with a manifest in a subdirectory (e.g. `package/napari/napari.yaml`) seem to have some metadata (e.g. supported data, plugin type) missing. Some of our plugins combine a `core` submodule with a `napari` submodule, so this structure is important to us. 

#### Steps/Code to Reproduce
Release a plugin with the yaml file in a submodule

#### Expected Results
The napari hub should be able to read manifest files anywhere that napari can. 

#### Actual Results
[brainreg](https://www.napari-hub.org/plugins/brainreg) is missing metadata from the manifest, but [brainglobe-napari-io](https://www.napari-hub.org/plugins/brainglobe-napari-io) isn't.

**Comment by manasaV3** [comment]
Thank you @adamltyson for sharing this issue with us.

Looking into the issue, it is because of how the [npe2 package](https://github.com/napari/npe2) we use for getting the napari manifest translates the module path into file path. They already have [a fix](https://github.com/napari/npe2/pull/336) for it merged in. Once the fix is released, the hub can get manifest metadata from subdirectories for the new plugin versions.

**Comment by adamltyson** [comment]
Thanks @manasaV3. I've [asked over on the napari zulip](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/Plugins.20showing.20up.20in.20napari.20plugin.20dialogue/near/416742639) if they have a plan to release soon.

**Comment by manasaV3** [comment]
@adamltyson We have updated [brainreg](https://www.napari-hub.org/plugins/brainreg) plugin's metadata. That addresses this issue, so I will close it out. Please don't hesitate to reach out to us if you have any other concerns. :)
