### ISSUE TITLE
Plugin author not shown in napari-hub

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [chanzuckerberg/napari-hub#1310]
#### Description
The author name is not shown for the plugin [napari-cosmos-ts](https://www.napari-hub.org/plugins/napari-cosmos-ts) despite the author name being correctly identified in [PyPI](https://pypi.org/project/napari-cosmos-ts/).

The author metadata is defined in `pyproject.toml` as (replace "..." with actual name and email):
```
[project]
authors = [
    {name = "...", email = "..."},
]
```

#### Expected Results
I expected napari-hub to find the author name given that it is identified on PyPI.

It seems silly to have to include another config file in the repo just for this metadata, but if that is the only solution, can someone please give me an example of what such a file should look like.

**Comment by manasaV3** [comment]
Hi there, 
Digging into this, I believe the reason for the author name not making it to the site is because of how the data from `pyproject.toml` is parsed.   
> When both email and name are provided, the value goes in [Author-email](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-author-email) or [Maintainer-email](https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata-maintainer-email) as appropriate, with the format {name} <{email}>.

ref: https://packaging.python.org/en/latest/specifications/pyproject-toml/#authors-maintainers

This leaves the author values as `None`, and we currently don't surface any author details for cases where the author name is `None`.


Until this bug is prioritized to be fixed on our end, a quick way to fix this would be to make the name and email into different entries as follows:

```
[project]
authors = [
    {name = "..."}, 
    {email = "..."},
]
```

Sorry for the inconvenience.

**Comment by marcel-goldschen-ohm** [comment]
Thanks @manasaV3.
