### ISSUE TITLE
right nav highlighting jumps to end

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#157]
*from June 2020 pre-launch bug bash*

**Created by**: justin

## Description 

when I click the next-to-last item on the right nav, if the last two sections are short, the last item gets highlighted. this happens on the about page as well as plugin pages

## Info

**Bug source**: wide

**Browser**: chrome

**PR**: *none*

## Attachments

https://dl.airtable.com/.attachments/f1adb5121031e79c3bdb51bfc8e8d8b7/c9fe1aa4/image.png

**Comment by codemonkey800** [comment]
@neuromusic This is because if the content is short enough, it'll default to the last item. This is to mirror the behavior of the current theme for napari.org:

https://user-images.githubusercontent.com/2176050/129072537-b69dd9c7-8626-48c9-9038-d97ae2486ea1.mp4

You can also see the same issue on the [About Team page](https://napari.org/community/team.html) for napari:

![image](https://user-images.githubusercontent.com/2176050/129072636-af2ec565-8562-4e94-9d87-998026bc6b90.png)

---

Another thing we could do is implement it similar to Docusaurus, but it means that if the last section's content is long enough, then it'll never get highlighted:

https://user-images.githubusercontent.com/2176050/129072863-8dd301cd-5bfd-4171-9218-9cd91c1fc0f2.mp4

I guess ultimately, what should be the correct behavior for the last section when content isn't long enough? cc: @liaprins-czi

**Comment by codemonkey800** [comment]
@liaprins-czi I also tagged you in case you had an idea on what the behavior should be 😃
