### ISSUE TITLE
Improve support for plugins with large numbers of categories

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#421]
As @haesleinhuepf noted, our current design is not well suited to plugins with large numbers of categories.

### Discussed in https://github.com/chanzuckerberg/napari-hub/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **haesleinhuepf** December 24, 2021</sup>
Hi all, 

just a suggestion about where the EDAM ontology entries are shown. At the moment, the user has to scroll down quite a bit until the actual documentation / readme of a plugin appears. I suggest to display all the useful metadata of plugins in other places (left/right), and not on top of the page. It's not urgent to work on this btw.

Happy Holidays!
Robert

![image](https://user-images.githubusercontent.com/12660498/147361155-8319ad13-349b-4d2b-94c9-8bebfff5b678.png)
</div>

**Comment by neuromusic** [comment]
designs here: https://www.figma.com/proto/1FVOiniqeJtTP4fjZZm4aO/Categories?page-id=745%3A468&node-id=756%3A2038&viewport=366%2C48%2C0.25&scaling=scale-down&starting-point-node-id=756%3A2038&show-proto-sidebar=1

**Comment by codemonkey800** [comment]
@lauramarcos fix for the alignment has been merged!

**Comment by codemonkey800** [comment]
already had this conversation with @lauramarcos but relaying it here:

> looks like in the plugin page, not even a category is displayed and the link is not aligned. Please let me know if any questions and thank you!

it's intentional, the category pill content is just really long lol @liaprins-czi  @neuromusic I wonder if there's something we can do at the content / design level to make things shorter for the pills? they can be quite long on mobile. the result of this is that at smaller screen sizes, you may not see pills at all:

<img width="300" src="https://user-images.githubusercontent.com/2176050/158875565-a7ae1a52-8ccd-4c58-a8e0-a65a84eaa9f7.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/2176050/158876898-4a31cc02-4b59-447b-92f5-8d90fede17bb.png">

@liaprins-czi if you already accounted for this in the design, please let me know so I can make a follow up PR 😃

**Comment by liaprins-czi** [comment]
Thanks for bringing my attention to this! Yes, it is true that mobile may not need to have the same information, but I think we could still show the first pill per category dimension  for mobile (first pill for Workflow step and first pill for Image modalities); it will have to probably go on the second line after the "Workflow steps:" or "Image modalities:" labels in most cases, but that is okay.

Here is a mockup:
<img width="704" alt="Screen Shot 2022-03-18 at 9 04 50 AM" src="https://user-images.githubusercontent.com/53277128/159040160-e60ca0b0-81a4-42ec-8a0a-7b69ce48c08d.png">
https://www.figma.com/file/1FVOiniqeJtTP4fjZZm4aO/Categories?node-id=904%3A522

Would that work @codemonkey800 ? Does it make sense to do, do you think?

**Comment by codemonkey800** [comment]
@liaprins-czi this looks good, I created a separate issue for this one: https://github.com/chanzuckerberg/napari-hub/issues/452
