### ISSUE TITLE
Make Plugin Preview notifications less persistent

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#422]
### Discussed in https://github.com/chanzuckerberg/napari-hub/discussions/389

<div type='discussions-op-text'>

<sup>Originally posted by **Czaki** January 14, 2022</sup>
I have installed napari-hub-bot in the PartSeg repository and it adds a nice preview of the napari hub page, but it happens for all pull requests, not only this one which touch description:

https://github.com/4DNucleome/PartSeg/pull/504#issuecomment-1013229837

I think, that is not an optimal solution. It should be easy to limit it only to PR which interacts with DESCRIPTION.md/Readme, etc.</div>

**Comment by neuromusic** [comment]
also, from another PR in the wild... 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/1245615/160749830-be2bd1b3-0c7c-473f-b5c2-46bf9666a478.png">

**Comment by codemonkey800** [comment]
@potating-potato @klai95 this is something that needs to be changed on the backend side. I originally implemented this in the MVP, but it didn't carry over during implementation because I think we decided to go with posting new comments instead

Probot has an extension for storing metadata in comments, but not sure if there's a Python equivalent. Still, we can probably recreate the functionality ourselves. It works by storing JSON data in a comment in the issue: https://github.com/probot/metadata#how-it-works

**Comment by Czaki** [comment]
Does it look solved?

**Comment by neuromusic** [comment]
@Czaki yes, this was fixed in #460 :D
