### ISSUE TITLE
Searching for plugins by author names may error after #592

### ISSUE THREAD

**Issue by lgan-czi** [chanzuckerberg/napari-hub#604]
#### Description
Searching for plugins by multiple author names in the top search bar will become slightly harder once https://github.com/chanzuckerberg/napari-hub/pull/592 lands. Now, you can’t search for plugins using multiple author names  unless you add a | between them. 

#### Steps/Code to Reproduce
Go to the [dev environment](https://dev-improve-author-splitting-frontend.dev.imaging.cziscience.com/?sort=recentlyUpdated&page=1) for #592 and search for a plugin with multiple authors using the first names of two or more authors. You should get no results. This can be compared with searched on the actual hub [website](https://www.napari-hub.org/) too

#### Expected Results
Searching by multiple author first names should return the plugin both authors worked on.

#### Actual Results
No results are shown.

For example, searching for Andrea and Mark used to return the napari-sim-processor, but this will not happen with the new author splitting changes. I think this is because the search only works on text within one html element, and since author names are now in different li html elements, the search breaks.
![Screen Shot 2022-07-08 at 2 50 49 PM](https://user-images.githubusercontent.com/106401390/178336730-aa39fdda-c6f0-4b99-84a3-0fe09cd541d5.png)

Not sure how big of an issue this is though, because it can be overcome by adding a pipe character (|) in between the author names, and there are other, better ways to filter by author on the hub. 
![Screen Shot 2022-07-08 at 2 51 55 PM](https://user-images.githubusercontent.com/106401390/178340475-ada41001-186f-4d4e-a04e-1120729e2c34.png)

**Comment by lgan-czi** [comment]
Oh right, that makes sense. I guess we should still bundle a disclaimer or something to alert people about this? Because I guess searches that used to work now won't.

**Comment by neuromusic** [comment]
(also, I'd opt to consider this an "enhancement" not a "bug", as the functionality described is as intended albeit confusing perhaps)

**Comment by lgan-czi** [comment]
Updated!

**Comment by liaprins-czi** [comment]
> I guess a lot of searches that used to work now won't
Is there any way to change the default functionality so it can search across more than one field at a time without needing the "|" pipe symbol? This would be the fix that I think would ultimately aid the user's experience the most, if possible.

Otherwise yes I definitely think having a little info tooltip or similar could be helpful. What would we want to include in it, beside this particular search functionality across fields (and users likely wouldn't realize that multiple authors are each in a separate "field", if I am even understanding that correctly?), so we should be careful about how we explain it. But would we want anything else in the info tooltip, like how to change the search operator and which it is by default (AND vs OR when there's a space between inputs)?
