### ISSUE TITLE
Add TTL to preview page so we can clean up resources

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#672]
I remember us planning to have a TTL for preview pages, but I'm not sure if it was set up because I'm seeing old preview pages for the napari-demo repo:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/2176050/193125195-f01dd98e-e458-4530-8973-d43e2c177c93.png">

we should apply a TTL so that we can clean up old and unused resources, and so that people don't use it for hosting things long term

**Comment by richaagarwal** [comment]
I've added a new lifecycle rule to delete these after 30 days.  @neuromusic do you think there is a need to support a longer timeframe?

**Comment by richaagarwal** [comment]
The lifecycle rule I've configured hasn't been working for some reason.  I'm going to put back into the backlog for now and will revisit this later.

**Comment by richaagarwal** [comment]
After modifying the configuration with @manasaV3's help, things seem to be working and getting deleted as expected. If you are logged into AWS, you can view the lifecycle configuration [here](https://s3.console.aws.amazon.com/s3/management/napari-hub-prod/lifecycle/edit?region=us-west-2&id=expire-preview-pages).

It is set up so that anything that is older than 30 days expires (the "Expire current versions of objects" setting), and then we delete those expired objects after 1 day (the "Permanently delete noncurrent versions of objects" setting). I previously had it set up to the reverse - 1 day to expire and 30 days to delete, which is why my testing wasn't working.
