### ISSUE TITLE
Unresolved references for import statements

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#687]
#### Description
Since we now have two directories in the codebase, namely, `backend` and `plugins`, the IDE has trouble finding the content inside of them. For example, `backend.utils.conda` yields no error, while `utils.github` yields error of `Unresolved reference 'utils'`. This issue slows down development velocity, as engineers would have to fix them in order to run their code locally.

<img width="895" alt="Screen Shot 2022-10-06 at 6 37 57 PM" src="https://user-images.githubusercontent.com/70177777/194437233-b2b611a2-b106-4ab7-97f7-12edb4982252.png">

**Comment by DragaDoncila** [comment]
I think this is an issue now because we don't have a proper python project structure. I think both `plugins` and `backend` should live under a top level python code module, especially as we add more functionality. We've actually already run into this issue when first adding the `preview` directory, (see[ comment here](https://github.com/chanzuckerberg/napari-hub/pull/279#issuecomment-941626090)), but I guess `plugins` is an extra level again.
