### ISSUE TITLE
“Releases” section: Time since last release

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#703]

**Comment by liaprins-czi** [comment]
(Not yet final) designs for P1 updates are here:
https://www.figma.com/file/d3t84J9Uzmj0GZnYROzdQX/Activity-Dashboard?node-id=1623%3A2042

I think the only thing left is to align on the proposed time buckets for both metrics. I am proposing we use the same "granularity system" of time bucketing that we use for the first Usage metric ("X installs since publicly released [insert time bucket]") for consistency, and because I think the same granularity concerns are relevant for these releases metrics. But want to see what others think, too!

**Comment by richaagarwal** [comment]
@neuromusic Should we archive or close this issue since we don't have plans to pursue a "Releases" section at this time?
