### ISSUE TITLE
API: return installs count for the prior 30 days

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub#709]
Add new API endpoint to return installs count for the past 30 days (not including today).

### P0 implementation details
- Add an additional query to cron job (that will be introduced in https://github.com/chanzuckerberg/napari-hub/issues/664) to retrieve daily install counts (for past 30 days only) from Snowflake and write those to an additional file in the S3 folder.  
- Add a new API endpoint (similar to `/activity/<plugin>/stats`) that returns the installs count for the past 30 days.  This should just be a sum of what's in the S3 file since the filtering is happening as part of the query above. Align with Jeremy/front-end on expected variable naming for this.

### Dependencies
- https://github.com/chanzuckerberg/napari-hub/issues/664

**Comment by manasaV3** [comment]
## Implementation strategies for last 30 days install metric

- Run query along with daily job to fetch data on installs by month
- Store data in persistent storage

### Fetching the data:

The daily job that runs to capture the number of installs by month can be leveraged to also update the installs in last 30 days metric as well. 

**Query:**

```
SELECT 
    file_project, 
    COUNT(*) as num_downloads
FROM
    (
        SELECT 
            file_project,
            CONCAT(
                DETAILS,
                DETAILS_INSTALLER, DETAILS_INSTALLER_NAME, DETAILS_INSTALLER_VERSION,
                DETAILS_PYTHON,
                DETAILS_IMPLEMENTATION_NAME, DETAILS_IMPLEMENTATION_VERSION,
                DETAILS_DISTRO, DETAILS_DISTRO_NAME, DETAILS_DISTRO_VERSION, DETAILS_DISTRO_ID, DETAILS_DISTRO_LIBC, DETAILS_DISTRO_LIBC_LIB, DETAILS_DISTRO_LIBC_VERSION,
                DETAILS_SYSTEM, DETAILS_SYSTEM_NAME, DETAILS_SYSTEM_RELEASE,
                DETAILS_CPU,
                DETAILS_OPENSSL_VERSION,
                DETAILS_SETUPTOOLS_VERSION,
                DETAILS_RUSTC_VERSION
            ) AS details_all,
            to_date(timestamp) AS timestamp
        FROM 
            imaging.pypi.downloads
        WHERE 
            (details_all NOT LIKE '%aws%' AND details_all NOT LIKE '%-azure%' AND details_all NOT LIKE '%gcp%' AND details_all NOT LIKE '%amzn%')  
            AND details_installer_name = 'pip'
            AND project_type = 'plugin'           
    )   
WHERE timestamp > DATEADD(DAY , -30, CURRENT_DATE) 
GROUP BY file_project
ORDER BY file_project
```

### Storing the data:

#### Single s3 file:

Storing the data for the installs in the last 30 days for all the plugins in a single s3 file. This can be done by writing the result of the query directly into a s3 file. 

*Pros:*

- Similar implementation to past modules, so this would allow for faster velocity in implementation 

*Cons:*

- Would require loading all of the data in memory to find number of installs for a single plugin
- We will be moving away from this architecture in the future

#### Multiple s3 files:

As the lambda that would be fetching the monthly install data would also be fetching the last 30 days install metric, both the data would be available in memory. We could leverage that to create an s3 file for activity keyed on the plugin name/id. 

To implement this, we would create a dictionary keyed on the plugin-id for both the monthly_install data and the last_30 days install data. This would allow us to easily consolidate them and write into an s3 file.

Proposed structure for the s3 file:

```
{  
   "activity": {
        "last_30_day_installs": xx,
        "monthly_installs": [
            {
                "timestamp": 1234354546,
                "install_count": 123
            },
       ]
    } 
}
```

*Pros:*

- This would allow for loading only the required data to resolve the api call for an activity. Thereby reducing the latency on the api call and reduce the cost of file get on s3.
- This also sets us up for success when we decide to consolidate the api calls for activity to a single api call. 

*Cons:*

- Implementation is different from the past implementations and might require more time to understand any unexpected behaviour and tackle them.
- Would also require updates to existing api call for getting monthly install data
- We may be moving away from this architecture in the future

#### Storing data in persistent store:

Might not be suitable for the P0 implementation, due to heavy refactor that might be needed and the associated spike that would be needed.
