### ISSUE TITLE
Empty latest commit section in activity maintenance

### ISSUE THREAD

**Issue by codemonkey800** [chanzuckerberg/napari-hub#889]
If the latest timestamp commit is `null`, then the frontend will render nothing for the data. We should render some sort of placeholder or an alternative UI to indicate that there's no data for it yet

https://staging.napari-hub.org/plugins/napari-boxmanager
https://api.staging.napari-hub.org/metrics/napari-boxmanager

### API Response

<img width="364" alt="image" src="https://user-images.githubusercontent.com/2176050/217335855-8176c739-5e7b-4280-88d3-fdeb894d8e7d.png">

### Frontend

<img width="817" alt="image" src="https://user-images.githubusercontent.com/2176050/217335696-3e13da85-1cb6-44f5-89ed-8e4a861ce005.png">

**Comment by richaagarwal** [comment]
I think it makes sense to extend the "There is not yet enough data to display for this plugin" design for the commits **timeline**, if the github repo was created in the current month (if we don't have that in place already). For the **stats**, I think we should continue to display whatever data we have as we do with the PyPI downloads.

For the above case looks like it's linked to a repo that wasn't recently created and is still completely inactive. I don't think it would be correct to say that there is not yet enough data in that situation, for any of the sections. 

For the latest commit specifically, it might be worth a specific design or text like "No commits yet" or leaving out that section altogether. There is the additional context in the other section that there are "0 commits" so it at least makes sense that there isn't data there.

Curious if @Janeece has any suggestions!

**Comment by richaagarwal** [comment]
For awareness, there's a separate data issue with this particular plugin/repo that @bnelson-czi is looking into.  But I think this edge case is still worth discussing!

**Comment by Janeece** [comment]
@codemonkey800 @richaagarwal Given the sentence-like structure for the display, I like the idea of not showing "latest commits" if there are no commits; seems like the simplest + least redundant way to give the info. Down side is it will leave  a weird layout gap. 

The other options would work ok, but my concerns with those approaches are:
- Having the "there is not enough data" design would lack context without a label or make less sense in the sentence structure
- "no commits yet" is redundant with the "0 commits" content (as already pointed out), but i like it better than "not enough data" because its more explicit. 

I might be overlooking some context, so please feel free to push back!

**Comment by richaagarwal** [comment]
Completely forgot about this issue as we've been discussing fixes in https://github.com/chanzuckerberg/napari-hub/issues/1220. @codemonkey800 this is the issue you must've been referencing to when we chatted 😅

I've evolved my thinking since I left this comment - https://github.com/chanzuckerberg/napari-hub/issues/889#issuecomment-1421370978 - though, since in practice we've seen that if we don't have commits data for a plugin, it's due to either an error on our end or being unable to retrieve the data for whatever reason. I'm going to close this one out since it's now being tracked in #1220 and will be resolved by https://github.com/chanzuckerberg/napari-hub/pull/1223.
