### ISSUE TITLE
Filter maintenance.timeline to return data from expected date range based on limit

### ISSUE THREAD

**Issue by klai95** [chanzuckerberg/napari-hub#958]
`Problem`: If we take https://api.napari-hub.org/metrics/zarpaint as an example, we can see that a portion of data returned by the API is outside of the range of 12 months, as `limit=12` by default. https://github.com/chanzuckerberg/napari-hub/pull/960 is the PR that addresses the bug by filtering out maintenance data that falls outside of the expected data range.

**Comment by klai95** [comment]
> I'm not sure that `maintenance` data needs to be consistent with `usage` data. Could you clarify what the bug is?
> 
> Looking at the commented out tests, it looks like the test is expecting 12 `maintenance` entries for e.g. https://www.napari-hub.org/plugins/napari-assistant, but I think that is an issue with the test and not the functionality. There are 10 entries for it as expected since there was no data the past two months, and it renders correctly. I believe at some point we discussed that @codemonkey800 would fill in any missing months on his end, but might be worth clarifying that point.
> 
> cc @manasaV3

If we take https://api.napari-hub.org/metrics/zarpaint as an example, we can see that the first element of `maintenance.timeline` is `{
        "commits": 1,
        "timestamp": 1625097600000
      }`
      
The problem is that the timestamp is equivalent to `Thursday, July 1, 2021 12:00:00 AM` in GMT, and therefore falls out of the range of data we should return for the API endpoint. Therefore, the bug is that the API shouldn't return data that is out of the expected date range based on `limit`, and https://github.com/chanzuckerberg/napari-hub/pull/960 is the PR that addresses the bug.

Using the same case of https://api.napari-hub.org/metrics/zarpaint, the correct implementation would only return 6 valid items, assuming `limit=12` as our default value. I do agree with @richaagarwal that in this case it would be fine to just return those 6 items as is without padding the additional 6 items with default values, since @codemonkey800 fills them in already. 

However, I should bring up that @manasaV3's implementation for usage metrics, as seen in https://api.napari-hub.org/metrics/hesperos, fills in the default values, so that is the discrepancy between usage metrics (backend fills in default values )and maintenance metrics (frontend fills in default values), which is why in [this file](https://github.com/chanzuckerberg/napari-hub/blob/5c24b371f9f06fbfb199bed7e6535af8b76ea2e8/backend/bdd_tests/scenarios/metric.feature) the tests failed.

**Comment by klai95** [comment]
> @klai95 I understand how the two implementations are different and agree it's not ideal that we're inconsistent here. If we are going to address this, it's best to use a consistent definition of `limit`.
> 
> That said, a `limit` generally implies we return a list of items up to that limit. It's not obvious based on the parameter `limit` that it implies any kind of date range to validate against. If we want to only return items within a certain date range, we can do that, but let's not use `limit` to guide that.

I think there may be some confusion, as I believe we are saying the same thing just in a different way. To clarify, if `limit=12`, in the case of https://api.napari-hub.org/metrics/zarpaint, what I mean by data range is capturing only the data from March 2022 to February 2023, and not using `limit` as a parameter to specify some window of data range. 

Back to the issue itself in https://api.napari-hub.org/metrics/zarpaint, the bug is that currently in `maintenace.timeline`, there are data from 2021, which shouldn't be the case at all, and this issue is addressing that problem.

**Comment by richaagarwal** [comment]
@klai95 I was saying something slightly different, but I don't have any issue with your proposed changes.  

What I was trying to say is that we return the past 12 (or less) values right now in your current implementation, which for that particular plugin means going back into 2021.  I don't think the variable name `limit` or anything else in the function is explicitly suggesting that we would take the `limit` value and convert that to the past _limit_ months, but I understand that initially that was the intention behind it, and that is how it is implemented for `usage`.   Since the frontend is doing the bulk of the validation here, I don't see this as a bug, but I do agree the inconsistency is confusing.

If this ticket is more about being consistent with the `usage` implementation (which I agree is a good idea), I would ask that the function handles missing data similarly as well, so perhaps you can sync with Jeremy and Manasa on that and handle any necessary changes regarding that in https://github.com/chanzuckerberg/napari-hub/pull/960. (That may mean removing the handling of missing data for `usage` or adding it for `maintenance` or some other solution). 

It might also be good to consider a clearer variable name and/or add some docstrings on what exactly the `limit` is intended to do, since on its own it does leave room for ambiguity.
